spring:
  profiles:
    active: dev


  jpa:
    open-in-view: true #web请求下的懒加载问题
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
    properties:
      hibernate:
   #     format_sql: true
        enable_lazy_load_no_trans: true  #非web请求下的懒加载问题解决



  thymeleaf:
    cache: false  # 这个开发配置为false，避免改了模板还要重启服务器
  data:
    web:
      pageable:
        one-indexed-parameters: true  #true认为是基于1开始的分页，默认是从0开始的
        size-parameter: limit  #默认为size，可以重新命名（layui默认为limit）


  jackson:
    date-format: yyyy-MM-dd  #时间格式化
    time-zone: Asia/Chongqing #时区设置

